language: r
sudo: false
cache: packages

services:
  - couchdb
  - redis-server
  - mongodb
  - elasticsearch

before_script:
  - sleep 10

r_packages:
  - sofa
  - etseed
  - elastic
  - mongolite
  - redux

addons:
  apt:
    update: true
    packages:
      - libapparmor-dev
      - libhiredis-dev
      - redis-server

after_failure:
  - ./travis-tool.sh dump_logs

r_check_args: "--as-cran --run-dontrun"

notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    secure: MIahHdXUhj4BLer8KfpDN+PmSzLPak59m2xyBgHvJuHp9RFLpXcOToyE0CF1Lbt8caxlox0FSmuqfqa0s+HrQhYOB6uAcFunDVOGV//MJrkms53LZqCqo2wrvEBastmv4Xv7+e5vBSG+M4bzRdf5MWn8QBTzzPeyJLkuOuu9V20=
