language: r
sudo: false
cache: packages
dist: trusty
warnings_are_errors: false

addons:
  apt:
    packages:
      - libapparmor-dev
      - libhiredis-dev
      - redis-server

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=FALSE

services:
  - couchdb
  - mongodb
  - elasticsearch
  - redis-server

before_script:
  - sleep 10

r_packages:
  - sofa
  - elastic
  - mongolite

after_failure:
  - ./travis-tool.sh dump_logs

r_check_args: "--as-cran --run-dontrun"

notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    secure: MIahHdXUhj4BLer8KfpDN+PmSzLPak59m2xyBgHvJuHp9RFLpXcOToyE0CF1Lbt8caxlox0FSmuqfqa0s+HrQhYOB6uAcFunDVOGV//MJrkms53LZqCqo2wrvEBastmv4Xv7+e5vBSG+M4bzRdf5MWn8QBTzzPeyJLkuOuu9V20=
